# Site settings
title: CaskCoin
description: > # this means to ignore newlines until "baseurl:"
  CaskCoin combines blockchain technology with a physical asset investment in the form of maturing Irish
  Whiskey.
baseurl: ""
url: "http://www.caskcoin.com"

# User setting
owner: CaskCoin
email: info@caskcoin.com
# facebook_username: CaskCoin
twitter_username: CaskCoin
github_username: CaskCoin
copyright: CaskCoin

contact:
  name: CASKCOIN BELFAST LIMITED
  company_number: NI693312
  locality: 7 Rathfriland Road
  region: Bandbridge
  postal_code: BT32 3LH
  country_name: N. Ireland
# phone: 0141 849 2090

# Google Analytics
google_tracking_id: UA-112518593-1

# Build settings
markdown: kramdown

# exclude vendor for travis
exclude: [vendor]

plugins:
  - jekyll-sitemap
  - jekyll-feed
