- name: Cryptocurrency
  description: CaskCoin Belfast Limied is issuing asset backed EIP 1155 utility token, on behalf of Titanic Distillery. Each token will represent legal ownership of a case each of whiskey.
  icon: fa-btc

- name: Asset Backed
  description: Each token will be backed by physical Titanic Distillery Whiskey making this cryptocurrency unique.
  icon: fa-money

- name: Investment
  description: Good investments often come in the form of establishing ownership of rare products and holding onto those products as the supply continues to drop, or the quality continues to improve.
  icon: fa-bank

- name: Transparent
  description: In order to ensure complete transparency and to drive additional value to the assets, Caskcoin Belfast Limited will manage the management of miniting, issueing and deployment on the polygon chain.
  icon: fa-qrcode
